# Unique name for this workflow
name: CI on PR

permissions:
    actions: none
    pull-requests: write
    contents: write

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, edited, synchronize, reopened]
        branches-ignore:
            - prerelease/spring[2-9][0-9]
            - prerelease/summer[2-9][0-9]
            - prerelease/winter[2-9][0-9]

jobs:
    testingScript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/github-script@v4
              id: bumpVersion
              with:
                  script: |
                      const data = require("./sfdx-project.json");
                      function bumpVersion(data) {
                          const versionNumber = data.packageDirectories[0].versionNumber;
                          const [major, minor, patch, build] = versionNumber.split(".");
                          const nextPatch = parseInt(patch) + 1;
                          return [major, minor, nextPatch, build].join(".");
                      }
                      return bumpVersion(data);
            - uses: jossef/action-set-json-field@v1
              with:
                  file: sfdx-project.json
                  field: packageDirectories[0].versionNumber
                  value: ${steps.bumpVersion.output.result}
            - uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: $GITHUB_HEAD_REF
